services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/workspace:cached
      - pip-cache:/home/dev/.cache/pip
    working_dir: /workspace
    environment:
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - LLM_MODEL=gemma3:1b
      - EMBEDDING_PROVIDER=ollama
      - EMBEDDING_MODEL=nomic-embed-text
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    environment:
      - API_BASE_URL=http://api:8000
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
      - STREAMLIT_BROWSER_GATHERUSAGESTATS=false  
    command: streamlit run app/ui.py --server.port 8501 --server.address 0.0.0.0 --server.headless true
    ports:
      - "127.0.0.1:18501:8501"
    depends_on:
      - api

volumes:
  pip-cache: