[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = ["data", "data/*"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E501"]

[tool.ruff.format]
docstring-code-format = true